include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_print: true
    use_key_in_widget_constructors: true
    library_private_types_in_public_api: false
